<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <FrontendPublicRoot>..\..\..\ClientSide\bazarKoto\public\</FrontendPublicRoot>
    <WebRootPath>$(FrontendPublicRoot)</WebRootPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BazarKoto.Application\BazarKoto.Application.csproj" />
    <ProjectReference Include="..\BazarKoto.Contracts\BazarKoto.Contracts.csproj" />
    <ProjectReference Include="..\BazarKoto.Domain\BazarKoto.Domain.csproj" />
    <ProjectReference Include="..\BazarKoto.Infrastructure\BazarKoto.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Watch Remove="logs\**\*" />
    <Watch Remove="wwwroot\uploads\**\*" />
    <Watch Remove="$(FrontendPublicRoot)uploads\**\*" />
    <Content Remove="logs\**\*" />
    <Content Remove="wwwroot\uploads\**\*" />
    <Content Remove="$(FrontendPublicRoot)uploads\**\*" />
    <None Remove="logs\**\*" />
    <None Remove="wwwroot\uploads\**\*" />
    <None Remove="$(FrontendPublicRoot)uploads\**\*" />
  </ItemGroup>

  <Target Name="EnsureUploadDirectories" BeforeTargets="Build">
    <MakeDir Directories="$(FrontendPublicRoot)uploads\contact-screenshots\" />
  </Target>

</Project>
